Delos/urls.py
from django.conf.urls.i18n import i18n_patterns
from django.template.context_processors import static
from django.urls import path, include
from django.views.i18n import JavaScriptCatalog

from Delos import settings
from authentication import admin

urlpatterns = [
    path('i18n/', include('django.conf.urls.i18n')),

]

urlpatterns += i18n_patterns(
    # Needed for translations in Javascript
    path('jsi18n/', JavaScriptCatalog.as_view(), name='javascript-catalog'),
)

authentication/urls.py
from django.contrib.auth.views import LogoutView
from django.urls import path
from authentication.views import LoginView

app_name = 'authentication'

urlpatterns = [
    path('login/', LoginView.as_view(), name='login'),
    path('logout/', LogoutView.as_view(), name='logout'),
]

webcore/urls.py
from django.urls import path
from webcore.views import IndexView

app_name = 'webcore'

urlpatterns = [
    path('', IndexView.as_view(), name='index'),
]

app/todo/models.py
from django.db import models


# Create your models here.

class TaskModel(models.Model):
    name = models.CharField(max_length=100, blank=True)

authentication/models.py
# Delos/auth/models.py
from django.utils import timezone

from django.contrib.auth.models import AbstractBaseUser, PermissionsMixin, Permission, Group
from django.utils.translation import gettext_lazy as _
from authentication.manager.managers import CustomUserManager
from django.db import models

from customers.models import Teams


class User(AbstractBaseUser, PermissionsMixin):
    email = models.EmailField(
        unique=True,
        verbose_name=_('Email'),
        max_length=255,
        blank=False
    )
    first_name = models.CharField(
        max_length=50,
        verbose_name=_('First Name'),
        blank=True
    )
    last_name = models.CharField(
        max_length=50,
        verbose_name=_('Last Name'),
        blank=True
    )

    birth_date = models.DateField(verbose_name=_('Birth Date'), blank=True, null=True)
    phone_number = models.CharField(max_length=10, verbose_name=_('Phone Number'), blank=True)
    date_joined = models.DateTimeField(_("date joined"), default=timezone.now)
    team = models.ForeignKey(Teams, on_delete=models.SET_NULL, verbose_name=_('Team'), blank=True, null=True)
    is_active = models.BooleanField(default=True)
    is_staff = models.BooleanField(default=False)
    is_admin = models.BooleanField(default=False)

    # override groups and user_permissions fields
    groups = models.ManyToManyField(Group, related_name='customuser_groups', blank=True)
    user_permissions = models.ManyToManyField(Permission, related_name='customuser_user_permissions', blank=True)

    USERNAME_FIELD = 'email'
    objects = CustomUserManager()
    REQUIRED_FIELDS = []

    class Meta:
        db_table = 'user'
        verbose_name = _("user")
        verbose_name_plural = _("users")

    def __str__(self):
        return self.email

    @property
    def full_name(self):
        return f'{self.first_name} {self.last_name}'

    def has_perm(self, perm, obj=None):
        return True

    def has_module_perms(self, app_label):
        return True

authenticationBase/authenticationShared/models.py
# Delos/auth/models.py
from django.utils import timezone

from django.contrib.auth.models import AbstractBaseUser, PermissionsMixin, Permission, Group
from django.utils.translation import gettext_lazy as _
from authenticationBase.authenticationShared.manager.managers import CustomUserManager
from django.db import models


class User(AbstractBaseUser, PermissionsMixin):
    email = models.EmailField(
        unique=True,
        verbose_name=_('Email'),
        max_length=255,
        blank=False
    )
    first_name = models.CharField(
        max_length=50,
        verbose_name=_('First Name'),
        blank=True
    )
    last_name = models.CharField(
        max_length=50,
        verbose_name=_('Last Name'),
        blank=True
    )

    phone_number = models.CharField(max_length=10, verbose_name=_('Phone Number'), blank=True)
    date_joined = models.DateTimeField(_("date joined"), default=timezone.now)
    is_active = models.BooleanField(default=True)
    is_staff = models.BooleanField(default=False)
    is_admin = models.BooleanField(default=False)

    # override groups and user_permissions fields
    groups = models.ManyToManyField(Group, related_name='customuser_groups', blank=True)
    user_permissions = models.ManyToManyField(Permission, related_name='customuser_user_permissions', blank=True)

    USERNAME_FIELD = 'email'
    objects = CustomUserManager()
    REQUIRED_FIELDS = []

    class Meta:
        db_table = 'user'
        verbose_name = _("user")
        verbose_name_plural = _("users")

    @property
    def full_name(self):
        return f'{self.first_name} {self.last_name}'

    def has_perm(self, perm, obj=None):
        return True

    def has_module_perms(self, app_label):
        return True

customers/models.py
from django.db import models
from django.utils.translation import gettext_lazy as _
from django_countries.fields import CountryField
from django_tenants.models import TenantMixin, DomainMixin


class Tenant(TenantMixin):
    """
    Class for creating client models using TenantMixin.
    """
    name = models.CharField(max_length=100, unique=True)
    country = CountryField(verbose_name=_('Country'), null=True, blank=True)
    paid_until = models.DateField()
    is_active = models.BooleanField(default=True)
    on_trial = models.BooleanField()
    created_at = models.DateTimeField(auto_now_add=True)

    # default true. Schema will be automatically created and synced when it is saved
    auto_create_schema = True
    auto_drop_schema = True

    def __str__(self):
        return self.name

    class Meta:
        db_table = 'tenant'
        verbose_name = _('Tenant')
        verbose_name_plural = _('Tenants')


class Domain(DomainMixin):

    def __str__(self):
        return self.domain

    class Meta:
        db_table = 'domain'
        verbose_name = _('Domain')
        verbose_name_plural = _('Domains')


class Teams(models.Model):
    name = models.CharField(max_length=100, unique=True, blank=False)
    tenant = models.OneToOneField(Tenant, on_delete=models.SET_NULL, null=True)

    def __str__(self):
        return self.name

    class Meta:
        db_table = 'teams'
        verbose_name = _('Team')
        verbose_name_plural = _('Teams')

webcore/models.py
from django.db import models

# Create your models here.

authentication/forms.py
from django.core.exceptions import ValidationError
from django.utils.translation import gettext_lazy as _
from authentication.models import User
from django import forms


class LoginForm(forms.Form):
    email = forms.EmailField(label=_('Email'))
    password = forms.CharField(widget=forms.PasswordInput)


class RegisterForm(forms.ModelForm):
    password = forms.CharField(widget=forms.PasswordInput())
    confirm_password = forms.CharField(widget=forms.PasswordInput())

    class Meta:
        model = User
        fields = ('email', 'password')

    def clean(self):
        cleaned_data = super().clean()
        password = cleaned_data.get('password')
        confirm_password = cleaned_data.get('confirm_password')

        if password != confirm_password:
            raise ValidationError(_("Les mots de passe ne correspondent pas "))

        # Always return the full collection of cleaned data
        return cleaned_data

authentication/views.py
from django.contrib import messages
from django.contrib.auth import authenticate, login
from django.shortcuts import render, redirect
from django.views.generic import TemplateView, View
from authentication.forms import LoginForm


class LoginView(View):
    form_class = LoginForm
    template_name = 'authentication/login.html'

    def get(self, request, *args, **kwargs):
        form = self.form_class()
        return render(request, self.template_name, {'form': form})

    def post(self, request, *args, **kwargs):
        form = self.form_class(request.POST)
        context = {'form': form}
        if form.is_valid():
            email = form.cleaned_data['email']
            password = form.cleaned_data['password']
            user = authenticate(request, email=email, password=password)
            if user is not None:
                login(request, user)
                return redirect('webcore:index')
            else:
                messages.error(request, 'Invalid login credentials.')
        return render(request, self.template_name, context)

webcore/views.py
from django.shortcuts import render
from django.views.generic import TemplateView


# Create your views here.


class IndexView(TemplateView):
    template_name = 'webcore/index.html'

authentication/templates/authentication/login.html
{% load i18n static bootstrap5 %}
<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="UTF-8">
    <title>{{ app_name }} - {% trans 'Login' %}</title>
    <link href="{% static 'authentication/css/signin.css' %}" type="text/css" rel="stylesheet">
    {% bootstrap_css %}
    {% bootstrap_javascript %}
</head>
<body class="text-center">
<main class="form-signin w-100 m-auto">
    <form method="post" action="{% url 'authentication:login' %}">
        {% csrf_token %}
        <img class="mb-4" src="{% static 'authentication/img/netflix_simple.png' %}" alt="" width="72" height="57">
        <h1 class="h3 mb-3 fw-normal text-white">{% trans 'Please sign in' %}</h1>

        <div class="form-floating">
            <input type="email" class="form-control" id="id_email" name="email" placeholder="{% trans 'Email address' %}" >
            <label for="id_email">{% trans 'Email address' %}</label>
        </div>
        <div class="form-floating">
            <input type="password" class="form-control" id="id_password" name="password" placeholder="{% trans 'Password' %}">
            <label for="id_password">{% trans 'Password' %}</label>
        </div>

        <div class="checkbox mb-3">
        </div>
        <button class="w-100 btn btn-lg btn-primary" type="submit">{% trans 'Sign in' %}</button>
        <p class="mt-5 mb-3 text-muted">&copy; {{ copyright }}</p>
        {% if messages %}
        <div class="messages">
            {% for message in messages %}
            <div{% if message.tags %} class="{{ message.tags }}"{% endif %}>
                {{ message }}
            </div>
            {% endfor %}
        </div>
        {% endif %}
    </form>
</main>

</body>
</html>

templates/base.html
{% load i18n static bootstrap5 %}
<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="UTF-8">
    <title>{{ app_name }} - {% block title %}{% endblock %}</title>
    <!--Script block integration -->
    <link href="{% static 'css/navbar.css' %}" type="text/css" rel="stylesheet">
    {% bootstrap_css %}
    {% bootstrap_javascript %}
    {% block script %}{% endblock %}
</head>
<body class="{% block body_class %}{% endblock %}">

<!-- Include navbar -->
{% include 'navbar.html' %} 

<!-- content and script_end block -->
{% block content %}{% endblock %}
{% block script_end %}{% endblock %}
</body>
</html>

templates/index.html
<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="UTF-8">
    <title>Title</title>
</head>
<body>

</body>
</html>

templates/navbar.html
{% load i18n static bootstrap5 %}

<nav class="navbar navbar-expand-md navbar-dark fixed-top bg-dark">
  <div class="container-fluid">
    <a class="navbar-brand" href="{% url 'webcore:index' %}">{{ app_name }}</a>
    <button class="navbar-toggler" type="button" data-bs-toggle="collapse" data-bs-target="#navbarCollapse" aria-controls="navbarCollapse" aria-expanded="false" aria-label="Toggle navigation">
      <span class="navbar-toggler-icon"></span>
    </button>
    <div class="collapse navbar-collapse" id="navbarCollapse">
      <ul class="navbar-nav me-auto mb-2 mb-md-0">
        <li class="nav-item">
          <a class="nav-link active" aria-current="page" href="{% url 'webcore:index' %}">{% trans 'Home' %}</a>
        </li>
        <li class="nav-item">
          <a class="nav-link" href="#">Link</a>
        </li>
      </ul>

      <form class="d-flex" role="search">
        <input class="form-control me-2" type="search" placeholder="{% trans 'Search' %}" aria-label="Search">
        <button class="btn btn-outline-success" type="submit">{% trans 'Search' %}</button>
      </form>
    </div>
  </div>
</nav>

webcore/templates/webcore/index.html
{% extends 'base.html' %}
{% load i18n static %}

{% block title %}
	{% trans 'Home' %}
{% endblock %}

{% block body_class %}body-navbar{% endblock %}

{% block script %}{% endblock %}

{% block content %}

{% endblock %}

{% block script_end %}{% endblock %}